x=10
y=8
print(bin(x))
print(bin(y))
print(x&y)
print(bin(x&y))
print(x&y,bin(x&y))
print(x|y)
print(bin(x|y))
print(x|y,bin(x|y))
print(x^y)
print(x^y,bin(x^y))
x=15
y=12
print(bin(x))
print(bin(y))
print(x&y)
print(bin(x&y))
print(x&y,bin(x&y))
print(x|y)
print(bin(x|y))
print(x|y,bin(x|y))
print(x^y)
print(x^y,bin(x^y))