print("hello mukesh")
print('hello mukesh')
print("hello mukesh,welcome to new delhi street number,2245,sector,96 ")
print(90+80)
print("90+50")
print("hello mukesh","welcome to new delhi")
print("hello mukesh","welcome to noida",98)
print("hello advika","welcome to home",90+50)
print("hello shravan bhaiya","welcome to home","95+96")
print(10>9)