a=input("enter the value:- ")
print(a)
b=input("enter the value1:- ")
c=input("enter the value2:- ")
print(b+c)
a=int(input("enter the value1:- "))
b=int(input("enter the value2:- "))
print(a+b)
print(a*b)
a=float(input("enter the value1:- "))
b=float(input("enter the value2:- "))
print(a+b)
a=eval(input("enter the value1:- "))
b=eval(input("enter the value2:- "))
print(a+b)


